# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zy/git-project/objLeftNew

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zy/git-project/objLeftNew

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zy/git-project/objLeftNew/CMakeFiles /home/zy/git-project/objLeftNew/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zy/git-project/objLeftNew/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named objLeftNew

# Build rule for target.
objLeftNew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objLeftNew
.PHONY : objLeftNew

# fast build rule for target.
objLeftNew/fast:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/build
.PHONY : objLeftNew/fast

myGMM.o: myGMM.cpp.o

.PHONY : myGMM.o

# target to build an object file
myGMM.cpp.o:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/myGMM.cpp.o
.PHONY : myGMM.cpp.o

myGMM.i: myGMM.cpp.i

.PHONY : myGMM.i

# target to preprocess a source file
myGMM.cpp.i:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/myGMM.cpp.i
.PHONY : myGMM.cpp.i

myGMM.s: myGMM.cpp.s

.PHONY : myGMM.s

# target to generate assembly for a file
myGMM.cpp.s:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/myGMM.cpp.s
.PHONY : myGMM.cpp.s

objLeftDetectcpp.o: objLeftDetectcpp.cpp.o

.PHONY : objLeftDetectcpp.o

# target to build an object file
objLeftDetectcpp.cpp.o:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/objLeftDetectcpp.cpp.o
.PHONY : objLeftDetectcpp.cpp.o

objLeftDetectcpp.i: objLeftDetectcpp.cpp.i

.PHONY : objLeftDetectcpp.i

# target to preprocess a source file
objLeftDetectcpp.cpp.i:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/objLeftDetectcpp.cpp.i
.PHONY : objLeftDetectcpp.cpp.i

objLeftDetectcpp.s: objLeftDetectcpp.cpp.s

.PHONY : objLeftDetectcpp.s

# target to generate assembly for a file
objLeftDetectcpp.cpp.s:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/objLeftDetectcpp.cpp.s
.PHONY : objLeftDetectcpp.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/objLeftNew.dir/build.make CMakeFiles/objLeftNew.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... objLeftNew"
	@echo "... myGMM.o"
	@echo "... myGMM.i"
	@echo "... myGMM.s"
	@echo "... objLeftDetectcpp.o"
	@echo "... objLeftDetectcpp.i"
	@echo "... objLeftDetectcpp.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

